site_name: CSUFAstronomy101
nav:
  - Home: index.md
  - About: about.md
  - Modules:
      - Welcome: 
        - Welcome to the Universe: modules/welcome_universe.md
      - Our View of the Universe: 
        - Our Cosmic Address: modules/cosmic_address.md
        - Observing the Sky: modules/celestial_sphere.md
      - The Rhythm of the Sky:
        - Daily Motion of the Sky: modules/daily_motion_sky.md
        - Northern and Southern Skies: modules/northern_southern_skies.md
        - Seasonal Stars: modules/seasonal_stars.md
      - Seasons:
        - Solstices and Equinoxes: modules/solstices_equinoxes.md
#        - The Path of the Sun: modules/path_of_sun.md
        - Seasons on Earth: modules/seasons_on_earth.md
      - The Moon:
#        - The Moon: modules/the_moon.md
        - Moon Phases: modules/moon_phases.md
        - Eclipses: modules/eclipses.md
      - Wandering Stars:
        - Planets and Retrograde Motion: modules/retrograde_motion.md
        - Ancient Greek Astronomy: modules/ancient_astronomy.md
        - Parallax: modules/parallax.md
      - Orbits: 
        - Heliocentric Revolutions: modules/copernican_revolution.md
        - Kepler's Laws: modules/keplers_laws.md
        - Kepler's Third Law: modules/keplers_third_law.md
      - Motion and Gravity: 
        - Newton's Laws: modules/newtons_laws.md
        - Newton's Gravity: modules/gravity.md
        - Mass and Weight: modules/mass_weight.md
      - Gravity in Action:
        - Alien Worlds: modules/planets_near_far.md
        - Black Holes: modules/gravity_action.md 
        - Energy and Momentum: modules/energy_angular_momentum.md
      - Light and Telescopes: 
        - The Spectrum of Light: modules/spectrum_of_light.md
        - Telescopes: modules/telescopes.md
        - Earth's Atmosphere: modules/earths_atmosphere.md
      - Spectra of Light:
        - Types of Spectra: modules/spectra_types.md
        - Thermal Spectra: modules/thermal_spectra.md
        - Luminosity: modules/luminosity.md
      - Learning from Light:
        - Fingerprints of the Elements: modules/fingerprints_elements.md
        - Doppler Effect: modules/doppler_effect.md
      - Making Earth from Scratch:
        - The Early Universe: modules/early_universe.md 
        - Formation of the Elements: modules/formation_of_elements.md
        - Formation of the Solar System: modules/formation_of_solar_system.md
      - The Life of Stars: 
        - The Source of Starlight: modules/source_of_starlight.md
        - Surveying the Stars: modules/surveying_stars.md
        - The Life of Stars: modules/life_cycle_of_stars.md
      - The Death of Stars:
        - The Death of Stars: modules/death_of_stars.md
        - Neutron Stars and Black Holes: modules/neutron_stars_black_holes.md
        - Gravitational Waves: modules/gravitational_waves.md
  - Activities:
      - Our View of the Universe: activities/our_view_universe.md 
      - The Rhythm of the Sky: activities/rhythm_sky.md
      - Seasons: activities/seasons.md
      - The Moon: activities/moon.md
      - Wandering Stars: activities/wandering_stars.md
      - Orbits: activities/orbits.md
theme: 
  name: material
  palette: 
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

plugins:
  - mkdocs_quiz

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js